### ISSUE TITLE
Create Markdown Files for 2019 Posters and Presentations

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/undergrad-expo#2]
We need to create Markdown files for posters and presentations for the 2019 research and arts expo. 

## Set Up
- Clone this repository
- Download the metadata for the posters and presentations: https://northwestern.box.com/s/kz2wkxl8mm9aw6vva8iw2tyob842u6ee 
- Create a new branch for this work

### To Do

Create a markdown file (`.md`) for each row in the spreadsheet. The column headers in the spreadsheet represent the YAML keys we will use for the front-matter in the markdown files. Name each file according to its `title`, using all lowercase and hyphens to separate each word. 

The top of the markdown files will look something like this:

```
---
date:
title:
author:
collection:
...
---
```

### Notes about some of the fields

The `doi` field refers to the DOI created for the project in Arch. In order to get the DOI for the work, you need to find the project in the [collection in Arch](http://arch.library.northwestern.edu/collections/g158bh40z). Just copy everything after the `/` in the URL (e.g. `10.21985/N2M49W` and paste it in the `doi` field in the YAML front-matter. If the project is not in the collection in Arch, you do not need to have a `doi` field in the front-matter.

The collection field in the spreadsheet is **not** used for the YAML front-matter. This field refers to the location for where to save the file. For example, if a row in the spreadsheet contains "`_posters`" in the `collection` column, save the markdown file in the the `2019` folder of the `_posters` directory (e.g. `/_posters/2019/title-of-poster.md`). 

### Done when
- You have created markdown files and placed them in their appropriate project directories (`_posters` or `_presentations`) in the 2019 folder.
- You have submitted a PR with these new files

**Comment by echoe320** [comment]
Was unsure what to put for the college and the subject so I gave it my best guess. This should probably be checked.

**Comment by echoe320** [comment]
I could not find the poster for "The Effects of Bacillus thuringiensis and Lysinibacillus sphaericus on Low-Density Polyethylene" in the Undergrad Expo section in the Arch database, so i couldn't recover the doi. Also there is no information on the college or subject?

**Comment by echoe320** [comment]
Couldn't find the poster for "The Role of the Super Elongation Complex (SEC) in Epidermal Progenitor Maintenance" in the Arch as well, so no doi.

**Comment by echoe320** [comment]
Some of the dates are also set in the future, i.e. "Preschoolers' Creativity During STEM Play" date set for 2019-06-28. Wondering if this is intentional or if it is a mistake?

**Comment by echoe320** [comment]
Couldn't find the poster for "Preschoolers' Creativity During STEM Play" in the Arch.

**Comment by chrisdaaz** [comment]
@echoe320 thanks for taking down these notes. please submit a PR when you're ready and i'll investigate all the oddities.

**Comment by echoe320** [comment]
Couldn't find the presentation "Redundant Function of PduA and PduJ in Bacterial Microcompartment Formation" in the Arch.

**Comment by echoe320** [comment]
The excel spread sheet didnt have an entry for funding for the presentation "Looking Homeward: The Troubled Nostalgia of Chiang Kai-shek Memorial Hall".

**Comment by echoe320** [comment]
Solved in #3 .
